workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 30
    environment:
      groups:
        - google_credentials
      vars:
        BUILDOZER_VERSION: "1.5.0"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install Buildozer
        script: |
          pip install buildozer==$BUILDOZER_VERSION cython
      - name: Install system dependencies
        script: |
          if command -v brew &> /dev/null; then
            # macOS - Codemagic M2 machines have most dependencies pre-installed
            echo "Running on macOS, dependencies should be pre-installed"
          else
            # Linux
            sudo apt-get update
            sudo apt-get install -y -qq git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config libffi-dev libssl-dev build-essential
          fi
      - name: Set up Android SDK
        script: |
          # Find and use Java 11 for Android SDK compatibility
          if [ -d "/Library/Java/JavaVirtualMachines/temurin-11.jdk" ]; then
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
          elif [ -d "/Library/Java/JavaVirtualMachines/zulu-11.jdk" ]; then
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
          elif [ -d "/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk" ]; then
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
          else
            echo "Java 11 not found, using default Java"
            export JAVA_HOME=$JAVA_HOME
          fi
          echo "Using Java: $JAVA_HOME"
          echo "Java version:"
          $JAVA_HOME/bin/java -version
          
          # Add JAXB dependencies for Android SDK compatibility
          JAXB_JAR=$JAVA_HOME/jmods/javax.xml.bind.jmod
          if [ -f "$JAXB_JAR" ]; then
            echo "JAXB module found at $JAXB_JAR"
          else
            echo "JAXB module not found, downloading dependencies..."
            curl -L -o jaxb-api.jar https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
            curl -L -o jaxb-impl.jar https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.1/jaxb-impl-2.3.1.jar
            curl -L -o jaxb-core.jar https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-core/2.3.1/jaxb-core-2.3.1.jar
            export CLASSPATH=$CLASSPATH:jaxb-api.jar:jaxb-impl.jar:jaxb-core.jar
          fi
          
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      - name: Build APK
        script: |
          buildozer -v android debug
    artifacts:
      - bin/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
