workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 30
    environment:
      groups:
        - google_credentials
      vars:
        BUILDOZER_VERSION: "1.5.0"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install Buildozer
        script: |
          pip install buildozer==$BUILDOZER_VERSION cython
      - name: Install system dependencies
        script: |
          if command -v brew &> /dev/null; then
            # macOS - Codemagic M2 machines have most dependencies pre-installed
            echo "Running on macOS, dependencies should be pre-installed"
          else
            # Linux
            sudo apt-get update
            sudo apt-get install -y -qq git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config libffi-dev libssl-dev build-essential
          fi
      - name: Build APK
        script: |
          buildozer -v android debug
    artifacts:
      - bin/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
